2021-12-26 19:32:13.311 +03 [1456] LOG:  starting PostgreSQL 14.1, compiled by Visual C++ build 1914, 64-bit
2021-12-26 19:32:13.330 +03 [1456] LOG:  listening on IPv6 address "::", port 5432
2021-12-26 19:32:13.330 +03 [1456] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-12-26 19:32:15.034 +03 [5140] LOG:  database system was shut down at 2021-12-26 19:31:10 +03
2021-12-26 19:32:15.750 +03 [1456] LOG:  database system is ready to accept connections
2021-12-26 21:07:35.071 +03 [14372] ERROR:  syntax error at or near "NOT" at character 40
2021-12-26 21:07:35.071 +03 [14372] STATEMENT:  SELECT * FROM products WHERE inventory NOT 0;
2021-12-26 21:31:26.866 +03 [14372] ERROR:  column "phone" does not exist at character 55
2021-12-26 21:31:26.866 +03 [14372] STATEMENT:  INSERT INTO products (name, price, inventory) VALUES (phone, 650, 10);
2021-12-26 21:42:25.564 +03 [14372] ERROR:  relation "producs" does not exist at character 13
2021-12-26 21:42:25.564 +03 [14372] STATEMENT:  DELETE FROM producs WHERE id = 7;
	SELECT * FROM producs;
2021-12-26 21:42:40.997 +03 [14372] ERROR:  relation "producs" does not exist at character 50
2021-12-26 21:42:40.997 +03 [14372] STATEMENT:  DELETE FROM products WHERE id = 7;
	SELECT * FROM producs;
2021-12-26 21:47:48.252 +03 [14372] ERROR:  syntax error at or near "=" at character 22
2021-12-26 21:47:48.252 +03 [14372] STATEMENT:  UPDATE products name = 'laptop dell', price = 1200, inventory = 25 WHERE id = 13;
	
2021-12-26 21:48:12.941 +03 [14372] ERROR:  syntax error at or near "=" at character 22
2021-12-26 21:48:12.941 +03 [14372] STATEMENT:  UPDATE products name = 'laptop dell', price = 1200, inventory = 25 WHERE id = 13;
	
2021-12-26 21:52:14.643 +03 [14372] ERROR:  column "ture" does not exist at character 31
2021-12-26 21:52:14.643 +03 [14372] STATEMENT:  UPDATE products SET is_sale = ture WHERE id > 13 RETURNING *;
	
2021-12-26 22:28:30.794 +03 [9156] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:28:30.794 +03 [9156] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:31:17.649 +03 [8116] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:31:32.715 +03 [12812] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:35:48.963 +03 [14700] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:35:50.414 +03 [12628] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:35:50.414 +03 [12628] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:35:52.494 +03 [15168] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:35:52.494 +03 [15168] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:35:54.558 +03 [14200] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:35:54.558 +03 [14200] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:35:56.700 +03 [8844] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:35:56.700 +03 [8844] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:35:58.784 +03 [7124] FATAL:  password authentication failed for user "postgres"
2021-12-26 22:35:58.784 +03 [7124] DETAIL:  Connection matched pg_hba.conf line 89: "host    all             all             ::1/128                 scram-sha-256"
2021-12-26 22:37:25.832 +03 [14548] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:39:01.798 +03 [7364] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:39:01.798 +03 [11100] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 22:39:01.799 +03 [7024] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-12-26 23:35:34.420 +03 [1456] LOG:  received fast shutdown request
2021-12-26 23:35:34.422 +03 [5268] ERROR:  canceling statement due to user request
2021-12-26 23:35:34.579 +03 [1456] LOG:  aborting any active transactions
2021-12-26 23:35:34.840 +03 [1456] LOG:  background worker "logical replication launcher" (PID 5268) exited with exit code 1
2021-12-26 23:35:35.062 +03 [5216] LOG:  shutting down
2021-12-26 23:35:38.961 +03 [1456] LOG:  database system is shut down
